project:
  type: manuscript
  output-dir: docs
  render: 
    - index.qmd
    - notebooks/causalizeR.qmd
    - notebooks/WHO-DON.qmd
    - notebooks/*.ipynb

manuscript:
  article: index.qmd
  code-links:
    - text: Github
      icon: github
      href: https://github.com/ntluong95/INFLUX

execute:
  freeze: auto

format:
  html:
    theme: [default, theme-light.scss] #superhero
    toc: true
    comments:
      hypothesis: true # comment side bar on the right
    citations-hover: true
    number-sections: true
    crossrefs-hover: true
    include-in-header:
      - file: myst.html
  docx: default